# Generated by Django 5.2.5 on 2025-09-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_echo_emp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emp',
        ),
        migrations.AlterField(
            model_name='echo',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='echo',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
